// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe72XVoRoact6QK79fXhUwPauoGgwTk3M',
    appId: '1:84151893414:web:b095222e2358cc530a6367',
    messagingSenderId: '84151893414',
    projectId: 'sis-system-e2f83',
    authDomain: 'sis-system-e2f83.firebaseapp.com',
    databaseURL: 'https://sis-system-e2f83-default-rtdb.firebaseio.com',
    storageBucket: 'sis-system-e2f83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADx-_UJSzyxkfekChkQKzduwUsTIxHJZM',
    appId: '1:84151893414:android:b82435f808695dfc0a6367',
    messagingSenderId: '84151893414',
    projectId: 'sis-system-e2f83',
    databaseURL: 'https://sis-system-e2f83-default-rtdb.firebaseio.com',
    storageBucket: 'sis-system-e2f83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuFuMFUTEccXtLQ9D7_SZtJIJokS_6dk',
    appId: '1:84151893414:ios:d723a9e61f5b65c90a6367',
    messagingSenderId: '84151893414',
    projectId: 'sis-system-e2f83',
    databaseURL: 'https://sis-system-e2f83-default-rtdb.firebaseio.com',
    storageBucket: 'sis-system-e2f83.appspot.com',
    iosClientId: '84151893414-3g03dkb0h4p8tl1g9n2fg8hs6p8fdh1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sisSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLuFuMFUTEccXtLQ9D7_SZtJIJokS_6dk',
    appId: '1:84151893414:ios:244e6b7ff1dd08810a6367',
    messagingSenderId: '84151893414',
    projectId: 'sis-system-e2f83',
    databaseURL: 'https://sis-system-e2f83-default-rtdb.firebaseio.com',
    storageBucket: 'sis-system-e2f83.appspot.com',
    iosClientId: '84151893414-a3oouq0gpb8dbcg65o7llkj1eatjdooj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sisSystem.RunnerTests',
  );
}
